# Generated by Django 4.1.4 on 2023-01-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_standard_size_product_unit_product_use_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_inventory',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
