# Generated by Django 4.1.7 on 2023-03-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_published_date_product_inventory_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
