# Generated by Django 4.1.7 on 2023-07-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_inventory',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='standard_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='use_days',
            field=models.IntegerField(),
        ),
    ]
