# Generated by Django 4.1.7 on 2023-07-17 12:36

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_userproduct_master_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='master_product',
            field=models.ForeignKey(limit_choices_to=product.models.limit_master_product_choices, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
