# Generated by Django 4.1.7 on 2023-07-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('ml', 'Milliliter'), ('l', 'Liter'), ('piece', 'Piece'), ('kg', 'Kilogram')], max_length=10),
        ),
    ]
