# Generated by Django 4.1.7 on 2023-08-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current_inventory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inventory_updated_date',
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
