# Generated by Django 4.1.7 on 2023-08-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20230803_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('ml', 'Milliliter'), ('l', 'Liter'), ('piece', 'Piece'), ('kg', 'Kilogram'), ('bottle', 'Bottle'), ('Pack', 'pack'), ('Tube', 'tube'), ('Stick', 'stick'), ('Jar', 'jar'), ('Box', 'box')], max_length=10),
        ),
    ]
