# Generated by Django 4.1.4 on 2023-01-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='standard_size',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='use_days',
            field=models.CharField(default=100, max_length=10),
            preserve_default=False,
        ),
    ]
