# Generated by Django 4.1.4 on 2023-01-18 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_current_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='published_date',
            new_name='inventory_updated_date',
        ),
    ]
