name: Build branch based on Cypress tests

on:
  push:
    branches:
      - main # you can replace this with your desired branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install
    
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    - name: Start server
      working-directory: ./frontend
      run: npm start &

    #- name: Run Cypress tests
     # working-directory: ./frontend
      #run:  npx cypress run
